---
# NB: don't set `language: haskell` here
# See https://github.com/hvr/multi-ghc-travis for more information
 
env:
 - GHCVER=7.6.3
 - GHCVER=7.8.2
 - GHCVER=head

matrix:
  allow_failures:
    - env: GHCVER=head

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.18 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-1.18 update
 - cabal-1.18 install --only-dependencies --enable-tests -f buildExecutable
 - cabal-1.18 install happy --constraint 'happy >=1.17'
 - cabal-1.18 install packdeps packunused

script:
 - cabal-1.18 configure --enable-tests -v2
 - cabal-1.18 build --ghc-options=-ddump-minimal-imports
 - cabal-1.18 test
 - cabal-1.18 check
 - cabal-1.18 sdist
 - packdeps stencil.cabal
 - packunused
